### ISSUE TITLE
Observe config failures in convolution

### ISSUE THREAD

**Issue by ce1adon** [ROCm/MIOpen#743] opened 2021-02-10 19:14 UTC
Observed the following failures in convolution when testing through driver. Please evaluate.

~~~
MIOpenDriver conv -n 1 -c 8 -H 1080 -W 1920 -k 16 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -F 1
Forward Convolution Failed: 0.00108118 > 1.5e-05

MIOpenDriver conv -n 1 -c 16 -H 540 -W 960 -k 16 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -F 1
Forward Convolution Failed: 0.000379819 > 1.5e-05

MIOpenDriver conv -n 1 -c 16 -H 270 -W 480 -k 16 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -F 1
Forward Convolution Failed: 0.00141181 > 1.5e-05

MIOpenDriver conv -n 1 -c 16 -H 270 -W 480 -k 16 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -F 1
Forward Convolution Failed: 0.00141181 > 1.5e-05

MIOpenDriver conv -n 1 -c 16 -H 540 -W 960 -k 16 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -F 1
Forward Convolution Failed: 0.000379819 > 1.5e-05

MIOpenDriver conv -n 1 -c 16 -H 1080 -W 1920 -k 16 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -F 1
Forward Convolution Failed: 0.000433639 > 1.5e-05
~~~

**Comment by zjing14** [comment] 2021-02-11 04:38
This is known issue due to compiler bugs. Fixed in ROCm 4.1.

**Comment by ce1adon** [comment] 2021-02-11 18:39
@zjing14 Thanks! Do you know which PR or ticket fixes this issue?

**Comment by atamazov** [comment] 2021-02-11 23:06
@ce1adon How do I reproduce the issue? ROCm version, GPU type, backend? And, if you know, suspected Solver. Thanks.

**Comment by ce1adon** [comment] 2021-02-11 23:33
@atamazov 
rocm 4.0, current MIOpen develop, gfx908, hip, not specified solver
BTW, @zjing14 said it's a known issue. I'm still checking for solution PR with him.

**Comment by atamazov** [comment] 2021-02-12 00:05
@ce1adon @zjing14 
> not specified solver

If you add `-t 1` to the MIOpenDriver command line, then it will print solver name. Of you can use `MIOPEN_LOG_LEVEL=5` and find Solver's name in the log.

> I'm still checking for solution PR with him.

If develop is failing with 4.0 but working fine with 4.1 RC, then:
- We do not have the workaround or fix in MIOpen
- The fix is in the compiler or in the runtime (perhaps it is possible to track it in Jira, but not necessarily).

___Q: Can we create a workaround so our next release wouldn't fail with ROCm 4.0?___

**Comment by atamazov** [comment] 2021-11-24 15:48
@ce1adon @zjing14 Any recommendations WRT how shall we handle this issue?

**Comment by atamazov** [comment] 2021-11-30 23:18
@ce1adon @zjing14 Advice?

**Comment by ppanchad-amd** [comment] 2024-03-18 14:17
@ce1adon Please check if this still an issue with latest ROCm 6.0.2? If not reproducible, please close ticket. Thanks!

**Closed** 2024-04-02 18:39 UTC
Labels: bug, urgency_low, value_unknown, correctness
