### ISSUE TITLE
Variant 4 intermittently fails in ctests and frameworks

### ISSUE THREAD

**Issue by daniellowell** [ROCm/MIOpen#479] opened 2020-10-01 04:44 UTC
http://ontrack-internal.amd.com/browse/SWDEV-253606

**Comment by daniellowell** [comment] 2020-10-01 04:45
Disabling via PR #478

**Comment by atamazov** [comment] 2021-11-24 16:33
AFAIU the original issue is about correctness, then a W/A (#478) has been merged, and the the issue is gone.

Now we need to restore performance with [value_high].

However I would like to keep the [bug] because the root reason of the issue was NOT found (see jira).

**Comment by atamazov** [comment] 2021-12-28 23:08
- The root reason of the original issue is not known, and
- The original issue is about "random issues", and
- I do not know if there is any connection between disabled "variant 4" and other "variants", so it is possible that these variants share some parts of the the kernel code or share the computation _approaches_ (e.g. how we do address calculations),

-- Then it is possible that random issues still persist in BN code. I am calling for investigation and proper fixing of the original issue at highest priority.

**Comment by atamazov** [comment] 2022-03-02 18:24
@junliume Please change value label to `unknown` and urgency label to `high`. Thanks.

**Comment by junliume** [comment] 2022-03-03 00:49
> @junliume Please change value label to `unknown` and urgency label to `high`. Thanks.

Done!

**Comment by huanrwan-amd** [comment] 2024-12-10 22:57
1. Running successfully for the benchmark scripts:
root@fd18a29d364e:/var/lib/jenkins/pytorch-micro-benchmarking# torchrun --nproc-per-node 2 micro_benchmarking_pytorch.py --network resnet50 --batch-size 64 --iterations 10
```
--------------------SUMMARY--------------------------
Microbenchmark for network : resnet50
--------This process: rank 1--------
Num devices: 1
Dtype: FP32
Mini batch size [img] : 32
Time per mini-batch : 0.02935183048248291
Throughput [img/sec] : 1090.2216139159536
```
2. As caffe2 is deprecated long back, the operator_test: “python3.6  spatial_bn_op_test.py TestSpatialBN.test_spatialbn_train_mode” is not avaiable anymore. Suggest to close the issue.

**Closed by huanrwan-amd** 2024-12-10 22:57 UTC
Labels: bug, performance, complexity_high, urgency_high, value_unknown
