### ISSUE TITLE
[Tensorflow] observed kernel_tests:pool_test_gpu failure after #1296

### ISSUE THREAD

**Issue by junliume** [ROCm/MIOpen#1642] opened 2022-07-22 01:46 UTC
It seems that PR #1296 has caused this issue in Tensorflow Unit Test Failure

**[Symptom]**
```
 # bazel test //tensorflow/python/kernel_tests:pool_test_gpu
```
shows that the following test has failed:
```
 [  FAILED  ] PoolingTest.testGradient1D
```
However, none of the MIOPEN environmental variables seem to be effective in the log output. The only info available in the log is:
```
 AssertionError: 0.500274658203125 not less than 0.01
```
**[Steps to Reproduce]:**
```
alias ptdrun=' sync && sudo /sbin/sysctl vm.drop_caches=3 && sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --ipc=host --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /data:/data --shm-size=64G'
	
ptdrun compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-hipclang:10405_ubuntu_py3_tensorflow_develop-upstream-QA-rocm53_cf1e7e6a
	
cd tensorflow/
	
bazel test //tensorflow/python/kernel_tests:pool_test_gpu

**Comment by junliume** [comment] 2022-07-22 02:26
Here are the collected commands:
```

./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 1 -c 1 -H 1 -W 4 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 1 -c 1 -H 1 -W 4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 1 -c 1 -H 1 -W 4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 1 -c 1 -H 1 -W 4 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 1 -c 1 -H 1 -W 4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 1 -c 1 -H 1 -W 4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 2 -t 1
./bin/MIOpenDriver pool -M 0 -n 4 -c 2 -H 1 -W 3 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 2 -t 1
./bin/MIOpenDriver pool -M 0 -n 4 -c 2 -H 1 -W 3 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -F 2 -t 1
```

and if I run them individually:
```
# ./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
**Input Flag: n Not Found !**
```

Hopefully this is helpful.

**Comment by junliume** [comment] 2022-07-25 20:49
@DrizztDoUrden this issue is blocking the release. Can we afford to revert PR #1296? We still have a few days though.

**Comment by atamazov** [comment] 2022-07-25 21:07
@junliume [Hint]
> However, none of the MIOPEN environmental variables seem to be effective in the log output...

```bash
bazel test \
--test_env MIOPEN_LOG_LEVEL=5 \
--test_env MIOPEN_FIND_MODE=normal \
--test_env MIOPEN_ENABLE_LOGGING=1 \
--test_env MIOPEN_ENABLE_LOGGING_MPMT=1 \
--test_env MIOPEN_COMPILE_PARALLEL_LEVEL=1 \
//tensorflow...
```

**Comment by junliume** [comment] 2022-07-25 21:26
> @junliume [Hint]
> 
> > However, none of the MIOPEN environmental variables seem to be effective in the log output...
> 
> ```shell
> bazel test \
> --test_env MIOPEN_LOG_LEVEL=5 \
> --test_env MIOPEN_FIND_MODE=normal \
> --test_env MIOPEN_ENABLE_LOGGING=1 \
> --test_env MIOPEN_ENABLE_LOGGING_MPMT=1 \
> --test_env MIOPEN_COMPILE_PARALLEL_LEVEL=1 \
> //tensorflow...
> ```

Thanks! Yes, I figured that out and generated the commands above :)

**Comment by atamazov** [comment] 2022-07-25 21:29
> ```
> MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
> **Input Flag: n Not Found !**
> ```

@junliume #1647 opened

**Comment by atamazov** [comment] 2022-07-25 21:33
@junliume It would be handy if log is collected and attached to the ticket. Suggested env:
```
--test_env MIOPEN_LOG_LEVEL=6 \
--test_env MIOPEN_ENABLE_LOGGING=1 \
--test_env MIOPEN_ENABLE_LOGGING_MPMT=1 \
```

**Comment by atamazov** [comment] 2022-07-25 21:39
@junliume 
> Can we afford to revert PR https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1296?

There should be no problems with Tensorflow build after reverting. However, I do not remember how important is the backward pooling support (which it implements).

Does reverting #1296 resolve the issue?

**Comment by junliume** [comment] 2022-07-26 17:30
@atamazov  the issue is pinned to #1296 but it might be difficult to revert it alone due to confict.

Here is the complete log:
[test.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9192059/test.zip)

**Comment by DrizztDoUrden** [comment] 2022-07-27 15:29
Just to reiterate: the problem is not caused by argument parsing: miopen is not called from cmdline from the test.

**Comment by DrizztDoUrden** [comment] 2022-07-27 15:32
Also corrected cmd lines from your comment are:
```
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 1x1x1x4 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 1x1x1x4 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -m max -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 2 -t 1
./bin/MIOpenDriver pool -M 0 --input 4x2x1x3 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 2 -t 1
./bin/MIOpenDriver pool -M 0 --input 4x2x1x3 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -F 2 -t 1
```
As a sidenote `-F 2` may require to be removed to be validated correctly by running both forward and backward.

**Comment by junliume** [comment] 2022-07-27 15:47
@DrizztDoUrden Thanks! Now one puzzle is resolved: the debug outputs (commands) are not the same as the one executed and are outdated (this should be resolved BTW).

The bigger problem is `AssertionError: 0.500274658203125 not less than 0.01` , I have tested that the starting point for this regression is #1296

**Comment by DrizztDoUrden** [comment] 2022-07-27 16:41
The last one indeed failes (on other GPUs as well) with this log:
<details>
  <summary>Log</summary>

```
> MIOPEN_LOG_LEVEL=6 ./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -t 1

MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -m avg -t 1
MIOpen(OpenCL): Info [get_device_name] Raw device name: gfx906:sramecc+:xnack-
MIOpen(OpenCL): Info [Handle] stream: 0x55c5224547e0, device_id: 0x55c5223faf00
MIOpen(OpenCL): Info [get_device_name] Raw device name: gfx906:sramecc+:xnack-
MIOpen(OpenCL): Info [Handle] stream: 0x55c522454a70, device_id: 0x55c5223faf00
MIOpen(OpenCL): Info [get_device_name] Raw device name: gfx906:sramecc+:xnack-
MIOpen(OpenCL): Info [Handle] stream: 0x55c5224551f0, device_id: 0x55c5223faf00
MIOpen(OpenCL): Info [get_device_name] Raw device name: gfx906:sramecc+:xnack-
MIOpen(OpenCL): Info [Handle] stream: 0x55c522460320, device_id: 0x55c5223faf00
MIOpen(OpenCL): Info [get_device_name] Raw device name: gfx906:sramecc+:xnack-
MIOpen(OpenCL): Info [Handle] stream: 0x55c522465ea0, device_id: 0x55c5223faf00
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetFound1_0] No invokers found for m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0
MIOpen(OpenCL): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 5.0.22042, MIOpen version 2.18.0.d19c2575c
MIOpen(OpenCL): Info2 [ValidateGcnAssemblerImpl] Running: '/opt/rocm/llvm/bin/clang --version'
MIOpen(OpenCL): Info2 [ValidateGcnAssemblerImpl] AMD clang version 14.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.0.0 22051 235b6880e2e515507478181ec11a20c1ec87945b)
MIOpen(OpenCL): Info2 [ValidateGcnAssemblerImpl] Target: x86_64-unknown-linux-gnu
MIOpen(OpenCL): Info2 [ValidateGcnAssemblerImpl] Thread model: posix
MIOpen(OpenCL): Info2 [ValidateGcnAssemblerImpl] InstalledDir: /opt/rocm/llvm/bin
MIOpen(OpenCL): Info2 [ValidateGcnAssemblerImpl] 
MIOpen(OpenCL): Info2 [SearchForSolutions] PoolingForward2d: Success.
MIOpen(OpenCL): Info2 [PrepareInvoker] Preparing kernel: mloPoolingG
MIOpen(OpenCL): Info2 [LoadProgram] Building OpenCL program: 'MIOpenPooling.cl', options: '-DMLO_POOLING_OP_ID=0 -DMLO_POOLING_KERNEL_SZ1=1 -DMLO_POOLING_STRIDE1=1 -DMLO_POOLING_KERNEL_SZ0=2 -DMLO_POOLING_STRIDE0=1 -DMLO_POOLING_N_HORIZ_OUT_PIX=1 -DMLO_POOLING_N_VERT_OUT_PIX=1 -DMLO_POOLING_GROUP_SZ0=8 -DMLO_POOLING_GROUP_SZ1=8 -DMLO_POOLING_INDEX_TYPE=uchar -DMLO_POOLING_INDEX_MAX=UCHAR_MAX -DMLO_POOLING_SAVE_INDEX -DUSE_IMG_INDEX=0 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP16x4=0 -DMIOPEN_USE_FP16x8=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=0 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -Werror -Wf,-Weverything -Wf,-Wno-cast-align -Wf,-Wno-cast-qual -Wf,-Wno-conversion -Wf,-Wno-double-promotion -Wf,-Wno-float-equal -Wf,-Wno-missing-prototypes -Wf,-Wno-pass-failed -Wf,-Wno-pedantic-core-features -Wf,-Wno-reserved-id-macro -Wf,-Wno-shorten-64-to-32 -Wf,-Wno-sign-compare -Wf,-Wno-sign-conversion -Wf,-Wno-unused-function -Wf,-Wno-unused-macros -Wf,-Wno-declaration-after-statement -cl-std=CL1.2
MIOpen(OpenCL): Info2 [Log] Kernel MIOpenPooling.cl Compile Time, ms: 235.273
MIOpen(OpenCL): Info2 [Register] Invoker registered for algorithm m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and solver PoolingForward2d
MIOpen(OpenCL): Info2 [SetAsFound1_0] Solver PoolingForward2d registered as find 1.0 best for miopenPooling2dForward in m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_i1_dt1_ker1x2_str1x1_it0_nout2_tile1x1_grp8x8_glb8x8x4_wsidx0 and algorithm miopenPooling2dForward
GPU Kernel Time Forward Pooling Elapsed: 0.004640 ms
Forward Pooling Verifies on CPU and GPU
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetFound1_0] No invokers found for m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0
MIOpen(OpenCL): Info2 [SearchForSolutions] PoolingBackward2d: Success.
MIOpen(OpenCL): Info2 [PrepareInvoker] Preparing kernel: mloPoolingAveBwd
MIOpen(OpenCL): Info2 [LoadProgram] Building OpenCL program: 'MIOpenPoolingBwd.cl', options: '-DMLO_POOLING_OP_ID=0 -DMLO_POOLING_KERNEL_SZ1=2 -DMLO_POOLING_STRIDE1=1 -DMLO_POOLING_KERNEL_SZ0=1 -DMLO_POOLING_STRIDE0=1 -DMLO_POOLBWD_N_HORIZ_OUT_PIX=1 -DMLO_POOLBWD_N_VERT_OUT_PIX=1 -DMLO_POOLBWD_GROUP_SZ0=8 -DMLO_POOLBWD_GROUP_SZ1=8 -DMLO_POOLING_INDEX_TYPE=uchar -DMLO_POOLING_INDEX_MAX=UCHAR_MAX -DUSE_IMG_INDEX=0 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP16x4=0 -DMIOPEN_USE_FP16x8=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=0 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -Werror -Wf,-Weverything -Wf,-Wno-cast-align -Wf,-Wno-cast-qual -Wf,-Wno-conversion -Wf,-Wno-double-promotion -Wf,-Wno-float-equal -Wf,-Wno-missing-prototypes -Wf,-Wno-pass-failed -Wf,-Wno-pedantic-core-features -Wf,-Wno-reserved-id-macro -Wf,-Wno-shorten-64-to-32 -Wf,-Wno-sign-compare -Wf,-Wno-sign-conversion -Wf,-Wno-unused-function -Wf,-Wno-unused-macros -Wf,-Wno-declaration-after-statement -cl-std=CL1.2
MIOpen(OpenCL): Info2 [Log] Kernel MIOpenPoolingBwd.cl Compile Time, ms: 115.063
MIOpen(OpenCL): Info2 [Register] Invoker registered for algorithm m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and solver PoolingBackward2d
MIOpen(OpenCL): Info2 [SetAsFound1_0] Solver PoolingBackward2d registered as find 1.0 best for miopenPooling2dBackward in m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
MIOpen(OpenCL): Info2 [GetInvoker] Returning an invoker for problem m0_dt1_xd2x2x1x5_xs10x5x5x1_yd2x2x1x4_ys8x4x4x1_dxd2x2x1x5_dxs10x5x5x1_dyd2x2x1x4_dys8x4x4x1_ker1x2_str1x1_pad0x0_it0_wsidx0 and algorithm miopenPooling2dBackward
GPU Kernel Time Backward Pooling Elapsed: 0.005280 ms
Sqr error : 0.0001878624074 Max err: 0.0004189841420 at 0, 0, 0, 1 c_v = 0.000037294623 vs g_v = -0.000381689519
Difference : 4503599627370496.000000000000 too large (eps=4.000000000000) at 0,0, 0,0 c_v = 0.000228139383 vs g_v = 0.000456278765
gps@morpheus:~/build/MIOpen/linux-release$ 
```

</details>

**Comment by atamazov** [comment] 2022-07-27 19:29
@DrizztDoUrden 
> As a sidenote `-F 2` may require to be removed to be validated correctly by running both forward and backward.

FYI the same list updated, sorted and duplicates removed:
```
./bin/MIOpenDriver pool -M 0 -m avg --input 1x1x1x4 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m avg --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m avg --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m avg --input 2x2x1x5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -F 0 -i 1
./bin/MIOpenDriver pool -M 0 -m avg --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 0 -i 1
./bin/MIOpenDriver pool -M 0 -m avg --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m avg --input 4x2x1x3 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -F 0 -i 1
./bin/MIOpenDriver pool -M 0 -m max --input 1x1x1x4 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m max --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m max --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m max --input 2x2x1x5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m max --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 1 -i 1
./bin/MIOpenDriver pool -M 0 -m max --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 1 -i 1
```

**Comment by atamazov** [comment] 2022-07-27 20:43
I confirm that the following config
```
./bin/MIOpenDriver pool -M 0 -m avg --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 0 -i 1 -t 1
```
has issue
```
Sqr error : 0.0002637330075 Max err: 0.0004453622969 at 0, 0, 0, 1 c_v = 0.000050611212 vs g_v = 0.000495973509
Difference : 4503599627370496.000000000000 too large (eps=4.000000000000) at 0,0, 0,0 c_v = -0.000197375542 vs g_v = -0.000394751085
```
just after merging of #1296 (72d89b40e). Previous commit is 9860cb1e6.

**Comment by atamazov** [comment] 2022-07-27 20:48
Note that #1296 contains MIOpenDriver changes. I will revert them in 72d89b40e and double-check in order to make sure that the reason of the validation failure is changes in the library, NOT in the driver.

**Comment by atamazov** [comment] 2022-07-27 21:47
Confirmed that MIOpenDriver changes in #1296 are Ok, the reason is changes in the library.

**Comment by atamazov** [comment] 2022-07-27 21:51
The immediate reason of the [problem](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1642#issuecomment-1197346784) is incorrect build options for the backward pooling kernel. The solver produces  -DMLO_POOLING_KERNEL_SZ0=1  -DMLO_POOLING_KERNEL_SZ1=2 (instead of correct SZ0=2, SZ1=1).

**Comment by atamazov** [comment] 2022-07-27 21:53
Updated list of regressed cases for testing:
```
./bin/MIOpenDriver pool -M 0 -m avg --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 0 -i 1 -t 1
./bin/MIOpenDriver pool -M 0 -m avg --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 0 -i 1 -t 1
./bin/MIOpenDriver pool -M 0 -m avg --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 0 -i 1 -t 1
./bin/MIOpenDriver pool -M 0 -m avg --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 0 -i 1 -t 1
./bin/MIOpenDriver pool -M 0 -m max --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 1 -F 0 -i 1 -t 1
./bin/MIOpenDriver pool -M 0 -m max --input 1x1x1x4 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 0 -i 1 -t 1
./bin/MIOpenDriver pool -M 0 -m max --input 2x2x1x5 -y 1 -x 2 -p 0 -q 0 -v 1 -u 2 -F 0 -i 1 -t 1
```

**Comment by junliume** [comment] 2022-07-27 22:44
> 🔴 The immediate reason of the [problem](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1642#issuecomment-1197346784) is incorrect build options for the backward pooling kernel. The solver produces -DMLO_POOLING_KERNEL_SZ0=1 -DMLO_POOLING_KERNEL_SZ1=2 (instead of correct SZ0=2, SZ1=1).

Thanks, @atamazov ! Do we know which part would be responsible of fixing it?

**Comment by atamazov** [comment] 2022-07-27 22:51
@junliume There is one obvious place, but we still need to investigate the code rigorously and decide in what exact place the fix should be done. Please expect it soon, either from me or from @DrizztDoUrden

**Comment by atamazov** [comment] 2022-07-27 22:53
@junliume Obvious place: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1296/files?diff=split&w=1#r931642485

**Comment by DrizztDoUrden** [comment] 2022-07-28 00:28
Would fix the first thing in the morning

**Comment by DrizztDoUrden** [comment] 2022-07-28 11:30
Created #1659 which should solve the reported problem.

**Comment by DrizztDoUrden** [comment] 2022-07-28 11:31
Many thank to @atamazov for help here.

**Comment by atamazov** [comment] 2022-07-28 14:55
Similar but likely less urgent issue with asymmetric 3d pooling is opened, #1660.

**Comment by atamazov** [comment] 2022-08-03 21:54
@junliume Please reopen because regression tests were not added yet.

**Comment by atamazov** [comment] 2022-08-03 21:54
`urgency_high`, no milestone.

**Comment by junliume** [comment] 2022-08-17 07:25
@atamazov The regression tests are added? Shall we close this issue?

**Comment by ppanchad-amd** [comment] 2024-04-16 20:27
@atamazov Can we close this ticket? Thanks!

**Comment by atamazov** [comment] 2024-04-19 16:59
@junliume @ppanchad-amd This can be closed.

**Closed** 2024-04-19 17:38 UTC
Labels: bug, value_high, urgency_high
